//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCBonusLab15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public string MovieName { get; set; }
        public string MovieCat { get; set; }
        public string MovieDesc { get; set; }
        public string MovieLength { get; set; }
        public string MovieDate { get; set; }
        public byte[] MoviePic { get; set; }
    }
}
